projects:
  TraumaTrackerSync:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: 3wlaitsz7zhoriul6bchnfvrwm
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: us-east-2
        maxDepth: 2
      endpoints:
        prod: >-
          https://yvited6yi5glzj52x3obd6or5y.appsync-api.us-east-2.amazonaws.com/graphql
