projects:
  TraumaTracker2:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: pqigyusqzvblhfvctiv4mmp3je
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: us-east-2
        maxDepth: 2
      endpoints:
        prod: >-
          https://kvd7oke7affldfnntsyg2g3ckm.appsync-api.us-east-2.amazonaws.com/graphql
